/* Additional record code for Load generated by the OpenModelica Compiler OpenModelica 1.12.0~3-g9389f90. */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

