# Makefile generated by OpenModelica

# Simulations use -O3 by default
CC=/usr/bin/clang
CXX=/usr/bin/clang++
LINK=/usr/bin/clang -single_module -dynamiclib -flat_namespace
EXEEXT=
DLLEXT=.dylib
CFLAGS_BASED_ON_INIT_FILE=
DEBUG_FLAGS=
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS)  -O0 -march=native ${MODELICAUSERCFLAGS}    
CPPFLAGS="-I/Users/spinhalf/Documents/Modelica/OMTLMSimulator/bin/OpenModelica/Resources/Include" -I"/opt/openmodelica/include/omc/c" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=Driver -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=0 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
LDFLAGS=-L"/Users/spinhalf/Documents/Modelica/test/driver" -L"/opt/openmodelica/lib/x86_64-darwin15.4.0/omc" -L"/opt/openmodelica/lib" -Wl,-rpath,"/opt/openmodelica/lib/x86_64-darwin15.4.0/omc" -Wl,-rpath,"/opt/openmodelica/lib"   -L/usr/lib64 -lstdc++ -L/opt/openmodelica/lib -Wl,-headerpad_max_install_names -arch x86_64 -lSimulationRuntimeC -llapack -lblas -lm -lomcgc 
MAINFILE=Driver.c
MAINOBJ=Driver.o
CFILES=Driver_functions.c Driver_records.c \
Driver_01exo.c Driver_02nls.c Driver_03lsy.c Driver_04set.c Driver_05evt.c Driver_06inz.c Driver_07dly.c \
Driver_08bnd.c Driver_09alg.c Driver_10asr.c Driver_11mix.c Driver_12jac.c Driver_13opt.c Driver_14lnz.c \
Driver_15syn.c Driver_16dae.c Driver_17inl.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) Driver.makefile Driver_literals.h Driver_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that Driver_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) Driver_functions.h Driver_literals.h $(OFILES)
	$(CC) -I. -o Driver$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) -L"/Users/spinhalf/Documents/Modelica/test/driver"  "-L/opt/openmodelica/lib/x86_64-darwin15.4.0/omc" "-L/opt/openmodelica/lib/" "-L/Users/spinhalf/.openmodelica/binaries/TLM" "-L/Users/spinhalf/Documents/Modelica/OMTLMSimulator/bin/OpenModelica/Resources/Library/x86_64-darwin" "-L/Users/spinhalf/Documents/Modelica/OMTLMSimulator/bin/OpenModelica/Resources/Library/darwin64" "-L/Users/spinhalf/Documents/Modelica/OMTLMSimulator/bin/OpenModelica/Resources/Library" -ltlmopenmodelica $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f Driver_records.o $(MAINOBJ)

bundle:
	@tar -cvf Driver_Files.tar $(GENERATEDFILES)